apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gmr-mlops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/srija77/my-mlops-project.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: mlops

  syncPolicy:
    automated:
      prune: true        # Remove resources not in Git
      selfHeal: true     # Re-sync if someone edits live resources
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
